#!/bin/sh
fix() {
    local options="$(setxkbmap -query | grep 'options:' | rev | cut -d ' ' -f 1 | rev)"
 
    # Simulate the ungrab.
    setxkbmap -option grab:break_actions
    xdotool key XF86Ungrab
 
    # Restore previous options, because leaving grab:break_actions enabled
    # could otherwise introduce a security risk, possibly allowing screensavers
    # to be bypassed, as mentioned here: https://unix.stackexchange.com/a/40472
    setxkbmap -option # Reset options.
    setxkbmap -option "$options"
}


chrome=$(pgrep chrome)
brave=$(pgrep brave)


if [ -n "$chrome" ]; then
        browser=chromium
elif [ -n "$brave" ]; then
        browser=Brave
fi

if [[ "$1" == "1" ]]; then
	hyprctl dispatch workspace 1
	#hyprctl dispatch focuswindow kitty
	hyprctl dispatch movecursortocorner 4
	fix
elif [[ "$1" == "2" ]]; then
	hyprctl dispatch workspace 2
	hyprctl dispatch focuswindow $browser
	hyprctl dispatch movecursortocorner 4
	fix
elif [[ "$1" == "3" ]]; then
	hyprctl dispatch workspace 3
	hyprctl dispatch focuswindow Steam
	hyprctl dispatch movecursortocorner 4
	fix
elif [[ "$1" == "4" ]]; then
	hyprctl dispatch workspace 4
	hyprctl dispatch focuswindow Spotify
	hyprctl dispatch movecursortocorner 4
	fix
elif [[ "$1" == "5" ]]; then
	hyprctl dispatch workspace 5
	hyprctl dispatch focuswindow discord
	hyprctl dispatch movecursortocorner 4
	fix
elif [[ "$1" == "6" ]]; then
	hyprctl dispatch workspace 6
	hyprctl dispatch focuswindow telegramdesktop
	hyprctl dispatch movecursortocorner 4
	fix
elif [[ "$1" == "7" ]]; then
	hyprctl dispatch workspace 7
	hyprctl dispatch focuswindow lutris
	hyprctl dispatch movecursortocorner 4
elif [[ "$1" == "8" ]]; then
	hyprctl dispatch workspace 8
	hyprctl dispatch focuswindow Transcribe
	hyprctl dispatch movecursortocorner 4
	fix
elif [[ "$1" == "9" ]]; then
	hyprctl dispatch workspace 9
	hyprctl dispatch focuswindow net.sourceforge.mumble.mumble
	hyprctl dispatch movecursortocorner 4
	fix
elif [[ "$1" == "g" ]]; then
	hyprctl dispatch workspace name:game
	hyprctl dispatch focuswindow gamescope
	hyprctl dispatch movecursortocorner 4
fi
